print("************************************")
print("Python can help us solve many problems. For example:")
print("1. If you get $10 a week in one year, for two years, you will have:")
print(10*52*2)
print("2. If we split a $125 bill between you, me and Sarah:")
print(125/3)
print("3. If I write 8 lines of code a week for 8 weeks:")
print(8*8)
print("4. 5*5*5+10 is :")
print(5*5*5+10)
print("Amazing! Python is so clever!")
print("************************************")